FileVersion = 1

[Project]
Name = "Zlib"
TargetType = "BeefLib"
StartupObject = "Zlib.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Release/zlibstatic.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Release/*.lib\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release/zlibstatic.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Release/*.lib\")"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)/dist/Release/zlibstatic.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Release/*.lib\")"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/dist/Release/zlibstatic.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Release/*.lib\")"]
